---
title: "MetOffice DataPoint Parser"
author: "Abdelrahman Ibrahim"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages 

```{r, include=TRUE}
require(httr)
require(jsonlite)
require(sf)
require(tidyverse)
require(purrr)
```

## Get data

measurement stations: 

```{r , include=TRUE}
stations <- readr::read_csv("http://environment.data.gov.uk/flood-monitoring/id/stations.csv", show_col_types = FALSE) %>% 
  filter(parameter == "rainfall")%>%
  filter(stationReference != 'Not_Specified') %>%
  select(stationReference, lat, long)
head(stations)
```

Get the rainfall data:

```{r , include=FALSE }
#Initial call - Remove if(FALSE){} to run

if(FALSE){base_url <- 'https://environment.data.gov.uk/flood-monitoring/archive/readings-full-'
range <- seq(as.Date("2023/08/19"), as.Date("2023/11/22"), by = "days")
out_url <- apply(expand.grid(base_url, range, ".csv"), 1, paste, collapse = '')

rainfall_df <- readr::read_csv(out_url, col_select = c("stationReference","parameter", "value","date"), col_types = cols(stationReference = col_character(), date = col_date(), value =col_double())) %>%
  filter(parameter == "rainfall") %>%
  filter(stationReference != 'Not_Specified') %>%
  group_by(date, stationReference) %>%
  summarise(daily_rainfall = sum(value)) %>%
  full_join(stations, by = c("stationReference")) %>%
  drop_na()

head(rainfall_df)}

```


```{r , include=TRUE}
#Append rainfall data to the database
base_url <- 'https://environment.data.gov.uk/flood-monitoring/archive/readings-full-'
range <- seq(as.Date("2023/11/26"), as.Date("2023/11/29"), by = "days")
out_url <- apply(expand.grid(base_url, range, ".csv"), 1, paste, collapse = '')

rainfall_df <- readr::read_csv(out_url, col_select = c("stationReference","parameter", "value","date"), col_types = cols(stationReference = col_character(), date = col_date(), value =col_double())) %>%
  filter(parameter == "rainfall") %>%
  filter(stationReference != 'Not_Specified') %>%
  group_by(date, stationReference) %>%
  summarise(daily_rainfall = sum(value)) %>%
  full_join(stations, by = c("stationReference")) %>%
  drop_na()

head(rainfall_df)
```


## Append the daily rainfall database

```{r , include=TRUE}

rainfall_hist <- readr::read_csv((r"(2_processed_data\ea_daily_rainfall.csv)"), col_types = cols(stationReference = col_character(), date = col_date(), value =col_double()))
rainfall_df <- rbind(rainfall_hist, rainfall_df)
rainfall_df <-  unique(rainfall_df)
tail(rainfall_df)

write.table(rainfall_df, (r"(2_processed_data\ea_daily_rainfall.csv)"), sep = ",", row.names = FALSE)

```


## Calculate Antecedent Rainfall Index for all days

```{r , include=TRUE}
rainfall_list <- split(rainfall_df, as.factor(rainfall_df$stationReference)) %>%
  lapply(function(df) {
  df[order(df$date), ]
})

rainfall_list[[1]]
```


``` {r}
# Function to calculate Antecedent Participation Index (API) from a dataframe
calculateAPI <- function(data, rainfall_column, n) {
  
  # Extract the precipitation vector from the dataframe
  rainfall <- data[[rainfall_column]]
  
  # Initialize a vector to store API values
  api <- numeric(length(rainfall))
  
  # Calculate API for each day
  for (i in (n + 1):length(rainfall)) {
    api[i] <- sum(rainfall[(i - n):(i - 1)]) / n
  }
  
  return(api)
}

# Function to apply calculateAPI to each dataframe in a list
calculateAPIList <- function(df_list, rainfall_column, n) {
  # Apply calculateAPI to each dataframe in the list
  api_list <- lapply(df_list, function(df) {
    calculateAPI(df, rainfall_column, n)
  })
  
  # Add API values to each dataframe in the list
  df_list_with_api <- lapply(seq_along(df_list), function(i) {
    df <- df_list[[i]]
    api <- api_list[[i]]
    df$API <- c(rep(NA, n - 1), api)[1:nrow(df)] # Adjusted to ensure correct alignment 
    df <- subset(df, date > as.Date("2023-08-31")) # only include readings from 01/09/2023

    return(df)
  })
  
  return(df_list_with_api)
}


# calculate api for 14 antecedent days
n <- 14
df_list <- rainfall_list
rainfall_column <- "daily_rainfall"

# Apply calculateAPIList to the list of dataframes
api <- calculateAPIList(df_list, rainfall_column, n)

# Print the dataframes with API values
api[[1]]

```
```{r}
api_daily <- bind_rows(api)

# Convert the date column to a list index
api_daily <- split(api_daily, f = api_daily$date)

# Optionally, remove the date column from each dataframe in the list
api_daily <- lapply(api_daily, function(df) df[, -1])
names(api_daily)[40]
```
## Convert 
```{r}
df_to_sf <- function(df) {
  # Assuming 'long' and 'lat' are the columns containing coordinates
  sf_df <- st_as_sf(df, coords = c("long", "lat"), crs = 4326)
  sf_df <- st_transform(sf_df, crs = 27700)
  return(sf_df)
}

# Apply the function to each data frame in the list
api_sf <- lapply(api_daily, df_to_sf)
api_sf[40]

```

