---
title: "Landcover"
author: "Abdelrahman Ibrahim"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=TRUE}
require(terra)
require(sf)
require(tidyverse)
require(geojsonsf)
```

```{r , include=TRUE}
mm_bound <- geojson_sf(r"(1_raw_data\boundaries\National_Trust_Open_Data _Land_-_Always_Open.geojson)") %>%
  st_transform(mm_bound, crs = 27700)
plot(mm_bound)
```

```{r , include=TRUE}
landcover <- rast(r"(1_raw_data\landcover\landcover_25m_grid\data\LCM.tif)")[[1]] %>%
  terra::crop(mm_bound)
landcover
```

```{r}
lc_ac <- terra::subst(landcover, 6:8, 5) |>
  terra::subst(9:12, 6) |>
  terra::subst(13, 7) |>
  terra::subst(14, 8) |>
  terra::subst(9:12, 6) |>
  terra::subst(15:19, 9) |>
  terra::subst(20:21, 10)

plot(lc_ac)
  
  
```


```{r , include=TRUE}
writeRaster(landcover, (r"(2_processed_data\landcover_MRSDNM.tif)"), overwrite = TRUE)

writeRaster(lc_ac, (r"(2_processed_data\landcover_ac.tif)"), overwrite = TRUE)

```

#Load and process soil wetness data
```{r}

# Load the soil data
soil <- vect(r"(1_raw_data\Soil\wyfs_wetness\soil_wetness_processed.shp)")

ref_raster <- landcover

# Convert the shapefile to raster based on the sampling of the reference raster
r1 <- terra::rasterize(soil, field="wet_score", ref_raster)
r2 <- terra::rasterize(soil, field="runoff_con", ref_raster)

soil_rast <- c(r1,r2)

writeRaster(soil_rast, (r"(2_processed_data\soil_wetness.tif)"), overwrite = TRUE)




plot(soil_rast[[2]])
```

