---
title: "MetOffice DataPoint Parser"
author: "Abdelrahman Ibrahim"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages 

```{r, include=TRUE}
require(httr)
require(jsonlite)
require(sf)
require(tidyverse)
require(purrr)
```

## Get data
API key: c464dd77-dd2c-4dc1-8d6a-3f987c2d6a10
Get the hourly observation data:
```{r , include=TRUE}
obs = GET("http://datapoint.metoffice.gov.uk/public/data/val/wxobs/all/json/all?res=hourly&key=c464dd77-dd2c-4dc1-8d6a-3f987c2d6a10")
obs_df <- as.data.frame(fromJSON(rawToChar(obs$content))$SiteRep$DV$Location)%>%
  unnest(cols = c(Period)) %>%
  unnest(cols = c(Rep)) %>%
  mutate(value=as.Date(value, format = "%Y-%m-%d"))
names(obs_df)[20] <- "t_midnight"
obs_df

```
## Append the observation database

```{r , include=TRUE}
obs_hist <- read.csv((r"(2_processed_data\metoffice_weather_obs.csv)"))
obs <- rbind(obs_hist, obs_df)
obs <-  unique(obs)

write.table(obs, (r"(2_processed_data\metoffice_weather_obs.csv)"), sep = ",", row.names = FALSE)
```


```
## Create a surface of daily average observations using IDW interpolation

```{r , include=TRUE}
```

