---
title: "Wildfire Mapping_v2.0"
author: "Lex Comber and Abdelrahman Hegazy"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=TRUE}
## packages
require(sf)
require(tidyverse)
require(raster)
```
1. Create a bounding box:

```{r, include=TRUE}
# now define clip extent and make a polygon to clip the data
xmin = 395947
xmax = 409947
ymin = 405284
ymax = 419284
# define a closed box
my.box <- data.frame(
  Poly = c(rep("A",5)),
  X = c(xmin, xmax, xmax, xmin, xmin),
  Y = c(ymin, ymin, ymax, ymax, ymin))
# my.poly
# then make polygon 
my.poly <- sfheaders::sf_polygon(
  obj = my.box, x = "X", y = "Y", polygon_id = "Poly"
)
# assign pOSGB projection
st_crs(my.poly) <- 27700
```

2. Extract daily rainfall data for 2022 
```{r, include=TRUE}
rain_files <- list.files( path = r"(1_raw_data\Climate Data\daily_rainfall_2022)", pattern = "\\.nc", full.names=TRUE)

rainfall <- lapply(rain_files, function(x){
  r1 = raster(x)
  for(i in 1:nbands(r1)){
    r = raster(x, band = i)
    r = crop(r, my.poly)
    p = rasterToPoints(r)
	  # colnames(p)[3] = i
	  if(i == 1) rain = p
	  if(i != 1) rain = cbind(rain, p[, 3])}
colnames(rain) = c("x", "y", paste0("day", 1:nbands(r1)))
return(rain)
})

#remove x and y from the second month onwards
for (i in 2:length(rainfall))
  rainfall[[i]] <- rainfall[[i]][ , -c(1:2)]

head(rainfall[[1]])
```

```{r, include=TRUE}
# convert the list of metrices to a tibble
rainfall <- as_tibble(do.call(cbind, rainfall))
#rename columns to reflect the dates 
colnames(rainfall)[3:ncol(rainfall)] <- as.character(seq(as.Date("2022-01-01"), as.Date("2022-12-31"), "days"))
rainfall <- tibble::rowid_to_column(rainfall, "ID")
  
rainfall
```

```{r, include=TRUE}
write.table(rainfall , file = r"(2_processed_data\2022_daily_rainfall.csv)", sep = ",", row.names = FALSE)
```

3. Calculate Antecedent Rainfall Index
